### ISSUE TITLE
Adding a scroll to top button

### ISSUE THREAD

**Issue by Devemmy01** [MiracleFactory/official-website#15]
Scrolling back all the way to the top of the page can be a pain to some users.
I can add a scroll back to top button using vanilla JS if I can be assigned to this project Thank you.

**Comment by YuelinXin** [comment]
That's great advice @Devemmy01, it can definitely bring better accessibility. This project is still in its early stage so we haven't actually been using a JS framework(and we are severely lacking on our JS functions), but we need one. Maybe you can help us decide which to use, vanilla JS sounds good just for this top button.

You can fork the **dev** branch and add your implementation, then submit a pull request, we will get back to you ASAP. Don't forget to assign this issue to that PR :)

**Comment by Devemmy01** [comment]
Thanks for assigning me. I'll use Vanilla JS

**Comment by YuelinXin** [comment]
Hi @Devemmy01, I saw that you just forked our repo, I think you might need to fork the **dev** branch instead of **main** because we have a major PR from dev to main, it might cause a merging issue if you try to change main directly, thanks.

**Comment by Devemmy01** [comment]
Oh my bad. I'll fork the dev branch then

**Comment by Devemmy01** [comment]
I'm having some issues viewing the site
![p](https://user-images.githubusercontent.com/87545460/210672461-846c6369-d57f-4544-8f8c-eb0bc8ef0dcf.PNG)
![p2](https://user-images.githubusercontent.com/87545460/210672463-3b653e03-0942-42ac-a5b5-9a8d212e5955.PNG)

**Comment by YuelinXin** [comment]
Okay, so for installing the Python packages use: `pip install -r requirements.txt`, the `$` symbol in front is just the command line prompt. For Windows, running the app, use: `flask --app==application run`.

**Comment by Devemmy01** [comment]
it's still not working. I'm not a python person and I don't know my way around python files.
I'm based on Javascript for now. I guess that's why I'm still not getting it

**Comment by YuelinXin** [comment]
> it's still not working. I'm not a python person and I don't know my way around python files. I'm based on Javascript for now. I guess that's why I'm still not getting it

So what is your current output now?

**Comment by Devemmy01** [comment]
I need to be able to preview the site with live server before I can work on it

**Comment by YuelinXin** [comment]
Yes, that is true. If you really can't get it to work, you can either create a new html file in `/application/templates/ui_snippets/` that contains your button and JS code, or you can wait for me to write a document on how to run the app that explains everything in more detail.

**Comment by YuelinXin** [comment]
By the way, have you configured your `.env` file yet? You will need this configuration file to run the website.

**Comment by Devemmy01** [comment]
Let me create a new html file in /application/templates/ui_snippets/
